version: "3.8"
services:
  db:
    image: postgres:15.1-alpine3.17
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    command: -p $DB_PORT
    networks:
      - shortener
  shortener:
    depends_on:
      - db
    build: ./shortener
    environment:
      - NODE_ENV=$SHORTENER_NODE_ENV
      - PORT=$SHORTENER_PORT
      - PGHOST=db
      - PGPORT=$DB_PORT
      - PGUSER=$DB_USER
      - PGPASSWORD=$DB_PASSWORD
      - PGDATABASE=$DB_NAME
    networks:
      - shortener
      - gateway
  ui:
    build: ./ui
    environment:
      - NODE_ENV=$UI_NODE_ENV
    volumes:
      - ./ui/dist:/app/dist
  nginx:
    image: nginx:1.23.3-alpine
    volumes:
      - ./ui/dist:/usr/share/nginx/html
      - ./nginx/templates:/etc/nginx/templates
    environment:
      - SHORTENER_HOST=shortener
      - SHORTENER_PORT=$SHORTENER_PORT
    ports:
      - 80:80
    restart: always
    networks:
      - gateway
volumes:
  postgres-data:
networks:
  shortener:
  gateway: